---
title: "p8105_hw1_bp2678"
author: "Brady Pham"
date: 2023-09-22
output: github_document
## 
---

#Problem 1

```{r}
library(moderndive)
data("early_january_weather")

```

the variables for this dataset is year, month, day, hour, temp, humidity, wind direction,
wind speed, and pressure. 

```{r}
num_rows <- nrow(early_january_weather)
num_columns <- ncol(early_january_weather)

```

There are 15 columns and 358 rows! 

```{r}
mean_temperature <- mean(early_january_weather$temp, na.rm = TRUE)

```

The mean temperature 39.5821


```{r}
library (ggplot2)
library(tidyverse)
```

```{r yx_scatter}

scatterplot <- early_january_weather %>%
  ggplot(aes(x = time_hour, y =temp, color = humid)) + geom_point()
scatterplot
```

```{r}
ggsave(filename = "scatterplot.png",
       plot = scatterplot,           
       width = 6,                    
       height = 4)                 
```

#Problem 2 

```{r}
random_sample <- rnorm(10)
logical_vector <- random_sample > 0
character_vector <- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J")
factor_vector <- factor(c("red", "green", "blue", "red", "green", "blue", "red", "green", "blue", "red"),
                        levels = c("red", "green", "blue"))

   
```


